"use client";
import { useEffect, useState } from "react";
import { csrfHeader } from "@/features/auth/csrf";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";

type Status = { configured: boolean; status: string; lastSuccessAt?: string | null; reason?: string | null };
const messages: Record<string,string> = { configuration_missing: "Nicht eingerichtet", configuration_invalid: "Home-Assistant-Adresse ist ungültig.", authentication_failed: "Der Access Token wurde von Home Assistant abgelehnt.", dependency_unreachable: "Home Assistant konnte nicht erreicht werden.", dependency_error: "Home Assistant hat einen API-Fehler zurückgegeben.", invalid_response: "Die Home-Assistant-Antwort konnte nicht verarbeitet werden.", CORE_UNAVAILABLE: "Core ist momentan nicht erreichbar." };
export function HomeAssistantConnection() {
  const [status,setStatus]=useState<Status|null>(null),[url,setUrl]=useState("http://192.168.1.116:8123"),[token,setToken]=useState(""),[phase,setPhase]=useState("idle"),[probe,setProbe]=useState<{deviceCount?:number}|null>(null),[error,setError]=useState<string|null>(null),[confirm,setConfirm]=useState(false);
  async function load(){const r=await fetch("/api/integrations/home-assistant",{cache:"no-store"});setStatus(await r.json());}
  useEffect(()=>{const id=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(id)},[]);
  function invalidate(){setProbe(null);setError(null)}
  async function call(path:string){setPhase(path==="probe"?"testing":path==="connect"?"connecting":"syncing");setError(null);try{const r=await fetch(`/api/integrations/home-assistant/${path}`,{method:"POST",headers:{"Content-Type":"application/json",...csrfHeader()},body:path==="sync"?undefined:JSON.stringify({baseUrl:url,accessToken:token})});const v=await r.json();if(!r.ok)throw new Error(v.code??"INTERNAL_ERROR");if(path==="probe")setProbe(v);else{setToken("");setProbe(null);await load()}}catch(e){setError(messages[e instanceof Error?e.message:"INTERNAL_ERROR"]??"Verbindung konnte nicht geprüft werden.")}finally{setPhase("idle")}}
  async function disconnect(){setConfirm(false);setPhase("syncing");await fetch("/api/integrations/home-assistant",{method:"DELETE",headers:csrfHeader()});await load();setPhase("idle")}
  const connected=!!status?.configured&&status.status!=="unknown"&&status.reason!=="configuration_missing";
  return <section className="connection-card ha-connection-card" aria-live="polite"><div className="ha-connection-heading"><div><p className="eyebrow">Integration</p><h2>Home Assistant</h2></div><span className={`integration-kind integration-kind-local`}>{connected?"Verbunden":"Lokal"}</span></div>{error&&<p className="auth-error" role="alert">{error}</p>}{!connected?<div className="ha-connect-form"><label>Home-Assistant URL<input value={url} onChange={e=>{setUrl(e.target.value);invalidate()}} autoComplete="url" /></label><label>Access Token<input type="password" value={token} onChange={e=>{setToken(e.target.value);invalidate()}} autoComplete="off" /></label><p>Verwende einen Home-Assistant Long-Lived Access Token.</p><button disabled={!url||!token||phase!=="idle"} onClick={()=>void call("probe")}>{phase==="testing"?"Verbindung wird geprüft …":"Verbindung testen"}</button></div>:<div className="ha-connected-state"><p className="ha-success">✓ Home Assistant verbunden</p><p>Endpoint: {status?.reason??"gespeicherte Verbindung"}</p>{status?.lastSuccessAt&&<p>Letzte Synchronisation: {new Date(status.lastSuccessAt).toLocaleString()}</p>}<button disabled={phase!=="idle"} onClick={()=>void call("sync")}>{phase==="syncing"?"Synchronisiere …":"Jetzt synchronisieren"}</button><button className="danger" disabled={phase!=="idle"} onClick={()=>setConfirm(true)}>Verbindung trennen</button></div>}{probe&&<div className="ha-probe-result" role="status"><p>✓ Home Assistant erreichbar</p><p>✓ Authentifizierung erfolgreich</p><p>{probe.deviceCount??0} Geräte gefunden</p><button disabled={phase!=="idle"} onClick={()=>void call("connect")}>{phase==="connecting"?"Verbinde und importiere …":"Verbinden & importieren"}</button></div>}<ConfirmDialog open={confirm} onOpenChange={setConfirm} title="Home Assistant wirklich trennen?" description="Die gespeicherte Verbindung wird entfernt. Bereits importierte Geräte bleiben in Kyrion erhalten." confirmLabel="Trennen" cancelLabel="Abbrechen" pending={phase!=="idle"} onConfirm={()=>void disconnect()} /></section>;
}
