"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useWorkspace } from "@/components/app-shell";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";
import { DeviceControlDialog } from "@/components/device-control-dialog";
import { csrfHeader } from "@/features/auth/csrf";
import { isRoomList, Room } from "@/features/home/contracts";
import { IntegrationConnection, isConnectionList } from "@/features/integrations/contracts";

export default function HomePage() {
  const { t } = useWorkspace(); const [rooms, setRooms] = useState<Room[]>([]); const [connections, setConnections] = useState<IntegrationConnection[]>([]); const [selected, setSelected] = useState<IntegrationConnection | null>(null); const [editing, setEditing] = useState<Record<string,string>>({}); const [deleteRoom, setDeleteRoom] = useState<Room|null>(null); const [error, setError] = useState(false); const [pending, setPending] = useState(false);
  const load = useCallback(async () => { const [roomResponse, connectionResponse] = await Promise.all([fetch("/api/home/rooms", { cache: "no-store" }), fetch("/api/integrations/nanoleaf/connections", { cache: "no-store" })]); const roomValue: unknown = await roomResponse.json(); const connectionValue: unknown = await connectionResponse.json(); if (!roomResponse.ok || !connectionResponse.ok || !isRoomList(roomValue) || !isConnectionList(connectionValue)) throw new Error(); setRooms(roomValue); setConnections(connectionValue); }, []);
  useEffect(() => { let disposed=false; async function initialLoad(){try{const [roomResponse,connectionResponse]=await Promise.all([fetch("/api/home/rooms",{cache:"no-store"}),fetch("/api/integrations/nanoleaf/connections",{cache:"no-store"})]);const roomValue:unknown=await roomResponse.json();const connectionValue:unknown=await connectionResponse.json();if(!roomResponse.ok||!connectionResponse.ok||!isRoomList(roomValue)||!isConnectionList(connectionValue))throw new Error();if(!disposed){setRooms(roomValue);setConnections(connectionValue);}}catch{if(!disposed)setError(true);}}void initialLoad();return()=>{disposed=true;};}, []);
  async function createRoom(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form=event.currentTarget; const name=String(new FormData(form).get("name") ?? "").trim(); if(!name)return; setPending(true); const response=await fetch("/api/home/rooms",{method:"POST",headers:{"Content-Type":"application/json",...csrfHeader()},body:JSON.stringify({name})}); if(response.ok){form.reset();await load();}else setError(true);setPending(false); }
  async function rename(room: Room) { const name=editing[room.id]?.trim(); if(!name)return; setPending(true); const response=await fetch(`/api/home/rooms/${room.id}`,{method:"PATCH",headers:{"Content-Type":"application/json",...csrfHeader()},body:JSON.stringify({name})}); if(response.ok){setEditing(c=>{const n={...c};delete n[room.id];return n;});await load();}else setError(true);setPending(false); }
  async function removeRoom() { if(!deleteRoom)return;setPending(true);const response=await fetch(`/api/home/rooms/${deleteRoom.id}`,{method:"DELETE",headers:csrfHeader()});if(response.ok){setDeleteRoom(null);await load();}else setError(true);setPending(false); }
  async function assign(connectionId:string,roomId:string|null){setPending(true);const response=await fetch(`/api/home/connections/${connectionId}/room`,{method:"PUT",headers:{"Content-Type":"application/json",...csrfHeader()},body:JSON.stringify({roomId})});if(response.ok)await load();else setError(true);setPending(false);}
  const groups=[...rooms.map(room=>({id:room.id,name:room.name,room,items:connections.filter(item=>item.roomId===room.id)})),{id:"unassigned",name:t.homeUnassigned,room:null,items:connections.filter(item=>!item.roomId)}];
  return <section className="home-dashboard"><header><div><p className="eyebrow">Kyrion Home</p><h1>{t.homeTitle}</h1><p>{t.homeDescription}</p></div><form onSubmit={createRoom}><input name="name" maxLength={120} placeholder={t.homeRoomName} required/><button disabled={pending}>{t.homeCreateRoom}</button></form></header>{error&&<p className="auth-error">{t.homeError}</p>}<div className="room-grid">{groups.map(group=><section className="room-card" key={group.id}><div className="room-heading">{group.room&&editing[group.id]!==undefined?<input autoFocus value={editing[group.id]} onChange={e=>setEditing(c=>({...c,[group.id]:e.target.value}))}/>:<h2>{group.name}</h2>}<div>{group.room&&<><button onClick={()=>editing[group.id]!==undefined?void rename(group.room!):setEditing(c=>({...c,[group.id]:group.name}))}>{editing[group.id]!==undefined?t.homeSaveRoom:t.homeRenameRoom}</button><button className="danger" onClick={()=>setDeleteRoom(group.room)}>{t.homeDeleteRoom}</button></>}</div></div>{group.items.length===0?<p className="room-empty">{t.homeNoDevices}</p>:<div className="room-devices">{group.items.map(device=><article key={device.id} onClick={()=>setSelected(device)}><div><strong>{device.displayName}</strong><small>Nanoleaf · {device.endpointHost}</small></div><button>{t.homeOpenControls}</button><label onClick={e=>e.stopPropagation()}>{t.homeAssignRoom}<select value={device.roomId??""} disabled={pending} onChange={e=>void assign(device.id,e.target.value||null)}><option value="">{t.homeUnassigned}</option>{rooms.map(room=><option value={room.id} key={room.id}>{room.name}</option>)}</select></label></article>)}</div>}</section>)}</div><DeviceControlDialog connection={selected} open={selected!==null} onOpenChange={open=>{if(!open)setSelected(null);}}/><ConfirmDialog open={deleteRoom!==null} onOpenChange={open=>{if(!open)setDeleteRoom(null);}} title={t.homeDeleteRoom} description={t.homeDeleteRoomDescription} confirmLabel={t.homeDeleteRoom} cancelLabel={t.cancel} pending={pending} onConfirm={()=>void removeRoom()}/></section>;
}
