"use client";
import { Dialog } from "radix-ui";
import { useEffect, useState } from "react";
import { useWorkspace } from "@/components/app-shell";
import { csrfHeader } from "@/features/auth/csrf";
import { IntegrationConnection, isNanoleafScenes, isNanoleafState, NanoleafScenes, NanoleafState } from "@/features/integrations/contracts";

export function DeviceControlDialog({ connection, open, onOpenChange }: { connection: IntegrationConnection | null; open: boolean; onOpenChange: (open: boolean) => void }) {
  const { t } = useWorkspace(); const [state,setState]=useState<NanoleafState|null>(null); const [scenes,setScenes]=useState<NanoleafScenes|null>(null); const [brightness,setBrightness]=useState(50); const [color,setColor]=useState("#22d3ee"); const [kelvin,setKelvin]=useState(4000); const [pending,setPending]=useState(false); const [failed,setFailed]=useState(false);
  useEffect(()=>{if(!open||!connection)return;let disposed=false;Promise.all([fetch(`/api/integrations/nanoleaf/connections/${connection.id}/state`,{cache:"no-store"}),fetch(`/api/integrations/nanoleaf/connections/${connection.id}/scenes`,{cache:"no-store"})]).then(async([a,b])=>{const sv:unknown=await a.json();const cv:unknown=await b.json();if(!disposed&&a.ok&&isNanoleafState(sv)){setState(sv);setBrightness(sv.brightness??50);setKelvin(sv.colorTemperature??4000);}if(!disposed&&b.ok&&isNanoleafScenes(cv))setScenes(cv);if(!disposed&&(!a.ok||!b.ok))setFailed(true);}).catch(()=>{if(!disposed)setFailed(true);});return()=>{disposed=true;};},[connection,open]);
  if(!connection)return null;
  async function command(path:string,body:object,type:"state"|"scenes"){setPending(true);setFailed(false);const response=await fetch(`/api/integrations/nanoleaf/connections/${connection!.id}/${path}`,{method:"PUT",headers:{"Content-Type":"application/json",...csrfHeader()},body:JSON.stringify({...body,confirmed:true})});const value:unknown=await response.json().catch(()=>null);if(type==="state"&&response.ok&&isNanoleafState(value))setState(value);else if(type==="scenes"&&response.ok&&isNanoleafScenes(value))setScenes(value);else setFailed(true);setPending(false);}
  function applyColor(){const rgb=[1,3,5].map(i=>parseInt(color.slice(i,i+2),16)/255);const max=Math.max(...rgb),min=Math.min(...rgb),delta=max-min;let hue=0;if(delta){if(max===rgb[0])hue=60*(((rgb[1]-rgb[2])/delta)%6);else if(max===rgb[1])hue=60*((rgb[2]-rgb[0])/delta+2);else hue=60*((rgb[0]-rgb[1])/delta+4);}void command("color",{hue:Math.round((hue+360)%360),saturation:Math.round(max===0?0:delta/max*100)},"state");}
  return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="confirm-dialog-overlay"/><Dialog.Content className="device-dialog"><Dialog.Title>{connection.displayName}</Dialog.Title><Dialog.Description>{t.homeDeviceControl} · {connection.endpointHost}</Dialog.Description>{failed&&<p className="auth-error">{t.nanoleafError}</p>}<div className="device-power"><button disabled={pending} onClick={()=>void command("power",{on:true},"state")}>{t.nanoleafTurnOn}</button><button disabled={pending} onClick={()=>void command("power",{on:false},"state")}>{t.nanoleafTurnOff}</button><span>{state?`${state.on?t.homeOnline:t.nanoleafTurnOff} · ${state.brightness??"–"}%`:"…"}</span></div><div className="dialog-brightness"><label>{t.nanoleafBrightness}<strong>{brightness}%</strong><input type="range" min="0" max="100" value={brightness} onChange={e=>setBrightness(Number(e.target.value))}/></label><button disabled={pending} onClick={()=>void command("brightness",{brightness},"state")}>{t.nanoleafApplyBrightness}</button></div><div className="color-controls"><label><span>{t.nanoleafColor}</span><input type="color" value={color} onChange={e=>setColor(e.target.value)}/><button disabled={pending} onClick={applyColor}>{t.nanoleafApplyColor}</button></label><label><span>{t.nanoleafColorTemperature}</span><strong>{kelvin} K</strong><input type="range" min="1200" max="6500" step="100" value={kelvin} onChange={e=>setKelvin(Number(e.target.value))}/><button disabled={pending} onClick={()=>void command("color-temperature",{kelvin},"state")}>{t.nanoleafApplyTemperature}</button></label></div><section><h3>{t.nanoleafScenes}</h3><div className="scene-list">{scenes?.items.map(scene=>{const colors=scenes.previews[scene]??[];return <button className={`${scenes.active===scene?"active":""} ${colors.length?"has-preview":""}`} style={colors.length?{backgroundImage:`linear-gradient(135deg, ${colors.join(", ")})`}:undefined} disabled={pending} key={scene} onClick={()=>void command("scenes/select",{name:scene},"scenes")}><span>{scene}</span>{scenes.active===scene&&<small>✓ {t.nanoleafActiveScene}</small>}</button>;})}</div></section><Dialog.Close asChild><button className="dialog-close">{t.homeClose}</button></Dialog.Close></Dialog.Content></Dialog.Portal></Dialog.Root>;
}
