"use client";
import { Dialog } from "radix-ui";
import { useEffect, useState } from "react";
import { useWorkspace } from "@/components/app-shell";
import { csrfHeader } from "@/features/auth/csrf";
import { IntegrationConnection, isNanoleafScenes, isNanoleafState, NanoleafScenes, NanoleafState } from "@/features/integrations/contracts";

export function DeviceControlDialog({ connection, open, onOpenChange }: { connection: IntegrationConnection | null; open: boolean; onOpenChange: (open: boolean) => void }) {
  const { t } = useWorkspace(); const [state, setState] = useState<NanoleafState | null>(null); const [scenes, setScenes] = useState<NanoleafScenes | null>(null); const [brightness, setBrightness] = useState(50); const [pending, setPending] = useState(false);
  useEffect(() => { if (!open || !connection) return; let disposed = false; Promise.all([fetch(`/api/integrations/nanoleaf/connections/${connection.id}/state`, { cache: "no-store" }), fetch(`/api/integrations/nanoleaf/connections/${connection.id}/scenes`, { cache: "no-store" })]).then(async ([a,b]) => { const sv: unknown = await a.json(); const cv: unknown = await b.json(); if (!disposed && a.ok && isNanoleafState(sv)) { setState(sv); setBrightness(sv.brightness ?? 50); } if (!disposed && b.ok && isNanoleafScenes(cv)) setScenes(cv); }).catch(() => {}); return () => { disposed = true; }; }, [connection, open]);
  if (!connection) return null;
  async function command(path: string, body: object, type: "state" | "scenes") { setPending(true); const response = await fetch(`/api/integrations/nanoleaf/connections/${connection!.id}/${path}`, { method: "PUT", headers: { "Content-Type": "application/json", ...csrfHeader() }, body: JSON.stringify({ ...body, confirmed: true }) }); const value: unknown = await response.json().catch(() => null); if (type === "state" && response.ok && isNanoleafState(value)) setState(value); if (type === "scenes" && response.ok && isNanoleafScenes(value)) setScenes(value); setPending(false); }
  return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="confirm-dialog-overlay"/><Dialog.Content className="device-dialog"><Dialog.Title>{connection.displayName}</Dialog.Title><Dialog.Description>{t.homeDeviceControl} · {connection.endpointHost}</Dialog.Description><div className="device-power"><button disabled={pending} onClick={() => void command("power", { on: true }, "state")}>{t.nanoleafTurnOn}</button><button disabled={pending} onClick={() => void command("power", { on: false }, "state")}>{t.nanoleafTurnOff}</button><span>{state ? `${state.on ? t.nanoleafOnline : t.nanoleafTurnOff} · ${state.brightness ?? "–"}%` : "…"}</span></div><div className="dialog-brightness"><label>{t.nanoleafBrightness} <strong>{brightness}%</strong><input type="range" min="0" max="100" value={brightness} onChange={(e) => setBrightness(Number(e.target.value))}/></label><button disabled={pending} onClick={() => void command("brightness", { brightness }, "state")}>{t.nanoleafApplyBrightness}</button></div><section><h3>{t.nanoleafScenes}</h3><div className="scene-list">{scenes?.items.map(scene => <button className={scenes.active === scene ? "active" : ""} disabled={pending} key={scene} onClick={() => void command("scenes/select", { name: scene }, "scenes")}>{scene}{scenes.active === scene && <small>✓ {t.nanoleafActiveScene}</small>}</button>)}</div></section><Dialog.Close asChild><button className="dialog-close">{t.homeClose}</button></Dialog.Close></Dialog.Content></Dialog.Portal></Dialog.Root>;
}
