"use client";
/* eslint-disable react-hooks/exhaustive-deps, react-hooks/set-state-in-effect */
import { useEffect, useMemo, useState } from "react";
import { csrfHeader } from "@/features/auth/csrf";
import { useWorkspace } from "@/components/app-shell";
import type { Role } from "@/features/auth/permissions";
type Permission={key:string;resource:string;operation:string};
export default function RolesPage(){
 const {t,hasPermission}=useWorkspace(); const [roles,setRoles]=useState<Role[]>([]); const [catalog,setCatalog]=useState<Permission[]>([]); const [selected,setSelected]=useState<Role|null>(null); const [draft,setDraft]=useState<string[]>([]); const [name,setName]=useState(""); const [state,setState]=useState<"idle"|"saving"|"saved"|"error">("idle"); const [createState,setCreateState]=useState<"idle"|"saving"|"error">("idle"); const [errorCode,setErrorCode]=useState<string|null>(null);
 const load=()=>Promise.all([fetch("/api/rbac").then(r=>r.json()),fetch("/api/rbac?resource=permissions").then(r=>r.json())]).then(([r,p])=>{setRoles(r);setCatalog(p);if(!selected&&r[0]){setSelected(r[0]);setDraft(r[0].permissions)}});
 useEffect(()=>{void load()},[]); useEffect(()=>{if(selected)setDraft(selected.permissions)},[selected]); const grouped=useMemo(()=>catalog.reduce<Record<string,Permission[]>>((a,p)=>{(a[p.resource]??=[]).push(p);return a},{}),[catalog]);
 if(!hasPermission("roles:read"))return <section className="settings-stage"><div className="settings-card"><h1>{t.forbiddenTitle}</h1><p>{t.forbiddenDescription}</p></div></section>;
 async function create(){const trimmed=name.trim();if(trimmed.length<2){setErrorCode("ROLE_NAME_INVALID");return}setCreateState("saving");setErrorCode(null);const key=trimmed.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");const r=await fetch("/api/rbac/roles",{method:"POST",headers:{"Content-Type":"application/json",...csrfHeader()},body:JSON.stringify({key,name:trimmed,permissions:[]})});if(!r.ok){setCreateState("error");setErrorCode((await r.json().catch(()=>({}))).code??"ROLE_CREATE_FAILED");return}const role=await r.json();setRoles(current=>[...current,role]);setSelected(role);setDraft([]);setName("");setCreateState("idle")}
 async function save(){if(!selected||selected.system)return;setState("saving");const r=await fetch(`/api/rbac/roles/${selected.id}`,{method:"PUT",headers:{"Content-Type":"application/json",...csrfHeader()},body:JSON.stringify({key:selected.key,name:selected.name,permissions:draft})});if(!r.ok){setState("error");return}const updated=await r.json();setRoles(current=>current.map(x=>x.id===updated.id?updated:x));setSelected(updated);setState("saved")}
 async function remove(){if(!selected||selected.system||!window.confirm(t.roleDeleteConfirm))return;setErrorCode(null);const r=await fetch(`/api/rbac/roles/${selected.id}`,{method:"DELETE",headers:csrfHeader()});if(!r.ok){setErrorCode((await r.json().catch(()=>({}))).code??"ROLE_DELETE_FAILED");return}const remaining=roles.filter(x=>x.id!==selected.id);setRoles(remaining);setSelected(remaining[0]??null);setDraft(remaining[0]?.permissions??[])}
 const errorMessage=errorCode==="ROLE_IN_USE"?t.roleInUse:errorCode==="ROLE_NAME_INVALID"?t.roleNameInvalid:errorCode?t.roleActionError:null;
 return <section className="settings-stage"><div className="settings-card"><p className="eyebrow">{t.rolesTitle}</p><h1>{t.rolesTitle}</h1><p>{t.rolesDescription}</p>{hasPermission("roles:create")&&<div><input value={name} onChange={e=>setName(e.target.value)} placeholder={t.roleNamePlaceholder} maxLength={80}/><button type="button" onClick={()=>void create()} disabled={createState==="saving"}>{createState==="saving"?t.authPending:t.roleCreate}</button></div>}{errorMessage&&<p role="alert">{errorMessage}</p>}<div className="settings-grid">{roles.map(role=><button className="settings-link-card" key={role.id} onClick={()=>setSelected(role)}><strong>{role.name}</strong><small>{role.system?t.roleSystem:t.roleCustom} · {role.userCount}</small></button>)}</div>{selected&&<div><h2>{selected.name}</h2>{Object.entries(grouped).map(([resource,items])=><fieldset key={resource}><legend>{resource}</legend>{items.map(p=><label key={p.key} style={{display:"block"}}><input type="checkbox" disabled={selected.system||!hasPermission("roles:update")} checked={draft.includes(p.key)} onChange={e=>setDraft(e.target.checked?[...draft,p.key]:draft.filter(x=>x!==p.key))}/>{p.operation} <small>{p.key}</small></label>)}</fieldset>)}{!selected.system&&hasPermission("roles:update")&&<button type="button" onClick={()=>void save()} disabled={state==="saving"}>{state==="saving"?t.authPending:t.rolesSave}</button>}{!selected.system&&hasPermission("roles:delete")&&<button type="button" onClick={()=>void remove()}>{t.roleDelete}</button>}{state==="saved"&&<p role="status">{t.rolesSaved}</p>}{state==="error"&&<p role="alert">{t.rolesSaveError}</p>}</div>}</div></section>}
